name: gg
channels:
  - conda-forge
  - defaults
  - memfault
dependencies:
- python=3.7
- invoke=1.3
- semver=2.8.1
- cmake=3.14
- git=2.23
- gcc-arm-none-eabi=8.2019.q3.update
- doxygen=1.8.16
- ninja=1.9.0
- cpputest=3.8
- mkdocs=1.1
- pip=20.0
- pip:
    - -r docs/requirements.txt
